baseURL = "https://kruskallin.github.io"
languageCode = "en-us"
title = "Kruskal Lin"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "Undergraduate Student"
  interests="Coding, Math, Dancing, Piano"
  blog="http://kruskallin.github.io/blog"

[[params.affilation]]
  name = "Nanjing University"
  position = "Undergraduate Student"
  contact = "161250070@smail.nju.edu.cn"

[[params.affilation]]
  name = "AI Valley Research Institute"
  position = "Algorithm Engineer"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/kruskallin"


[[params.introduction.paragraph]]
  text="""I am student in Software Institute in Nanjing University advised by Prof. Yang Yu and Associate Prof. Jidong Ge. I embrace pragmatism and like thinking independently.
   """

#[[params.projects]]
#	[[params.projects.project]]
#		name = "Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor"
#		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id #ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
#		project_page = "https://myprojecthomepage.com"
#		code_link = "https://coderepo.com"
#		blog_link = "https://ablogpost.com"


#[[params.publications]]
#  year="Preprint"

#  [[params.publications.paper]]
#    name = "Enim nunc faucibus a pellentesque sit amet porttitor"
#    authors = "Ana Alvardo, William Worthley, __Hadi Sinaee__"
#    dest  = "Helga Zita Journal"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"


#[[params.publications]]
#  year="2019"

#  [[params.publications.paper]]
#		name = "Feugiat sed lectus vestibulum mattis ullamcorper velit sed"
#		authors = "Caroll Comes, __Hadi Sinaee__"
#		dest  = "Udo Madhu Journal"
#		link = "https://mypaperishere.com"
#		code_link = "https://thecoderepo.com"
#		blog_link = ""
